### ISSUE TITLE
Change the System Navigation Bar color alongside the (dark) theme

### ISSUE THREAD

**Issue by akirk** [Mosc/Glider#7]
I have my Android set to dark mode and the app theme works well for this but unfortunately on my device the bottom navigation bar (the triangle circle square one) remains very bright, both when changing the theme and when relaunching the app.

I've been trying to fix this myself but I haven't worked with Flutter before and thus unfortunately wasn't successful. Maybe this snippet can someone to implement it? https://gist.github.com/akirk/1a0a84a292c50b866dd5189e843d467e

Thanks!

**Comment by Mosc** [comment]
Interesting! Coincidentally, I've made some commits today to make the navigation bar translucent. This should allow the app to draw behind the bar on Android 11 and up, but I'd be curious to know if this improves your situation as well, as long as you're running at least Android 5. I don't have a device with a bright (white?) navigation bar on hand, so do you have a dev environment setup that allows you to test the current master branch on your device?

**Comment by akirk** [comment]
I've tested c5480ac06df653bbf532b0570ee3178a1d966b42, it does make things better (i.e. dark in dark mode and light in light mode, at least after an app restart). I run Android 10 so the bottom navigation bar isn't translucent.

<table><tr><td>
Glider dark mode + Android dark a11ff2e8e23530b1af3e3b855ddd876d1141811d
<img src="https://user-images.githubusercontent.com/203408/112111776-f3777b00-8bb4-11eb-8a39-aaafcb92afa0.jpg">
</td><td>
Glider light mode + Android light mode c5480ac06df653bbf532b0570ee3178a1d966b42
<img src="https://user-images.githubusercontent.com/203408/112109540-02a8f980-8bb2-11eb-9611-20c8562b528a.jpg" alt="Screenshot_20210323_082538_nl viter glider">
</td><td>
Glider dark mode + Android dark mode without app restart c5480ac06df653bbf532b0570ee3178a1d966b42:
<img src="https://user-images.githubusercontent.com/203408/112109669-24a27c00-8bb2-11eb-85e6-09b3fe06282a.jpg">
</td><td>
Glider dark mode + Android dark mode with a freshly started app c5480ac06df653bbf532b0570ee3178a1d966b42:
<img src="https://user-images.githubusercontent.com/203408/112109715-31bf6b00-8bb2-11eb-90a7-091466a85cb3.jpg">
</td></tr></table>

**Comment by Mosc** [comment]
Hmm, dark mode indeed looks fine (after a restart), but the light mode navigation bar looks... rough. Wonder if I can replicate the colored navigation bar in an emulator somehow. It's going to be difficult to fix properly otherwise.

**Comment by Porkepix** [comment]
Adding as an example, current F-droid release on Android 8, here's a screenshot where you can see the system bar offer white icons on white background, making it almost impossible to read. The problem happens to be in all the modes.

![Screenshot from 2021-05-03 23-25-10](https://user-images.githubusercontent.com/709500/116976994-29367600-acc2-11eb-93d1-5c5268ae6e6a.png)

I already reported similar bugs that were fixed in other applications, if that may help.

**Comment by Mosc** [comment]
Whoops, that's definitely not intended behavior. Seems like I should perform more testing on older versions. I've disabled the (attempted) translucency on Android versions below 11 in 2bf3dd2309c39f1476096fd8958e6e790ca1105c, which should also fix @akirk's issues.

Thanks for the additional information on this issue!

**Comment by akirk** [comment]
FWIW the white bar that I described in the original issue is back for quite a few versions already. Unfortunately I didn't take note which version brought it back. I've been placing my finger over the bottom bar at night, not to be blinded by the bright white :)

**Comment by Mosc** [comment]
I tried this out on a Samsung device myself and fixed it once and for all (fingers crossed) in 5da12ca8030016619a775d2404bdd41212aa5bfe. Previously the app did not force a specific navigation bar color for older Android versions, which defaulted to black on most devices, but Samsung decided it would be a good idea to default to white instead. Even in dark mode! Explicitly setting it to black made the situation significantly better on this Samsung device running on Android 9.

**Comment by akirk** [comment]
I can confirm that this is now fixed again in the latest version. Thanks!
